###
POST https://localhost:443/pdfs/createPDF HTTP/1.1
Content-Type: application/json

{
  "order" : {
    "id" : "fedb19f5-bd4c-4bfc-b2d1-212538319611",
    "number" : 10096,
    "dateCreated" : "2020-03-18T16:47:59.222Z",
    "currency" : "USD",
    "weightUnit" : "LB",
    "totals" : {
      "subtotal" : "50",
      "shipping" : "3",
      "tax" : "3",
      "discount" : "0",
      "total" : "56",
      "weight" : "30",
      "quantity" : 2
    },
    "billingInfo" : {
      "paymentMethod" : "PayPal",
      "externalTransactionId" : "tx_1806",
      "paymentProviderTransactionId" : "tx_1806",
      "address" : {
        "fullName" : {
          "firstName" : "John",
          "lastName" : "Smith"
        },
        "country" : "US",
        "city" : "New York",
        "zipCode" : "92544",
        "phone" : "+972 555234555",
        "email" : "sahiram@web.de"
      },
      "paidDate" : "2020-03-18T16:47:59.244Z"
    },
    "shippingInfo" : {
      "deliveryOption" : "Express",
      "estimatedDeliveryTime" : "Today",
      "shippingRegion" : "East coast",
      "shipmentDetails" : {
        "address" : {
          "fullName" : {
            "firstName" : "John",
            "lastName" : "Smith"
          },
          "country" : "US",
          "city" : "New York",
          "zipCode" : "92544",
          "phone" : "+972 555234555",
          "email" : "sahiram@web.de"
        },
        "discount" : "0",
        "tax" : "1",
        "priceData" : {
          "taxIncludedInPrice" : false,
          "price" : "3"
        }
      }
    },
    "read" : false,
    "archived" : false,
    "paymentStatus" : "PAID",
    "fulfillmentStatus" : "NOT_FULFILLED",
    "lineItems" : [ {
      "index" : 1,
      "quantity" : 2,
      "name" : "my product",
      "productId" : "a1f9d337-f831-4529-31e6-67db8fd4e1aa",
      "lineItemType" : "PHYSICAL",
      "options" : [ ],
      "customTextFields" : [ ],
      "weight" : "15",
      "sku" : "12345678",
      "discount" : "1",
      "tax" : "1",
      "priceData" : {
        "taxIncludedInPrice" : false,
        "price" : "5",
        "totalPrice" : "10"
      }
    }, 
    {
      "index" : 2,
      "quantity" : 4,
      "name" : "my product 2",
      "productId" : "a1f9d337-f831-4529-31e6-67db8fd4e1ab",
      "lineItemType" : "PHYSICAL",
      "options" : [ ],
      "customTextFields" : [ ],
      "weight" : "20",
      "sku" : "12345678",
      "discount" : "0",
      "tax" : "2",
      "priceData" : {
        "taxIncludedInPrice" : false,
        "price" : "10",
        "totalPrice" : "40"
      }
    } ],
    "activities" : [ {
      "type" : "ORDER_PLACED",
      "timestamp" : "2020-03-18T16:47:59.222Z"
    }, {
      "type" : "ORDER_PAID",
      "timestamp" : "2020-03-18T16:47:59.244Z"
    } ],
    "fulfillments" : [ ],
    "discount" : {
      "value" : "1"
    },
    "buyerLanguage" : "en",
    "channelInfo" : {
      "type" : "WEB"
    },
    "enteredBy" : {
      "id" : "e85274cf-047a-4989-baff-dac5e0c3971d",
      "identityType" : "USER"
    },
    "lastUpdated" : "2020-03-18T16:47:59.244Z"
  }
} 
